### ISSUE TITLE
Inducción 

### ISSUE THREAD

**Issue by LuisAlexisMorales** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-6#1]
[induccion-matematica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-6/files/13619169/induccion-matematica.pdf)

**Comment by josealfredo79** [comment]
La practica no es de induccion

**Comment by josealfredo79** [comment]
15
