### ISSUE TITLE
Mapa de karnaugh

### ISSUE THREAD

**Issue by JoseRodriguez-23620213** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-6#2]
[PRACTICA3-MAPASDEKARNAUGH.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-6/files/13641920/PRACTICA3-MAPASDEKARNAUGH.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
